# Generated by Django 3.2.4 on 2021-10-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='check',
            field=models.BooleanField(default=False),
        ),
    ]
