# Generated by Django 3.2.4 on 2021-10-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customer_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='time_off',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
