# Generated by Django 3.2.4 on 2021-09-27 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_slug'),
        ('shops', '0001_initial'),
        ('product_detail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detail_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_expiry', models.DateField(blank=True, null=True)),
                ('ingredient', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('active_ingredients', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.active_ingredients')),
                ('body_care', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.body_care')),
                ('brand_beaty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.brand_beaty')),
                ('brand_clothes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.brand_clothes')),
                ('brand_mobile_gadgets', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.brand_mobile_gadgets')),
                ('camera_selfie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.cameraselfie')),
                ('category', models.ForeignKey(limit_choices_to=models.Q(('choice', True)), on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('collar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.collar')),
                ('cropped_top', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.cropped_top')),
                ('dress_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.dress_style')),
                ('expiry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.expiry')),
                ('formula', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.formula')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.item')),
                ('main_camera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.maincamera')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.material')),
                ('memory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.memory')),
                ('occasion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.occasion')),
                ('operating_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.operating_system')),
                ('origin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.origin')),
                ('packing_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.packing_type')),
                ('pants_length', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.pants_length')),
                ('pants_style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.pants_style')),
                ('petite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.petite')),
                ('phone_features', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.phone_features')),
                ('processor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.processor')),
                ('ram', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.ram')),
                ('sample', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.sample')),
                ('screen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.screen')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.season')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.shop')),
                ('sim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.sim')),
                ('skirt_length', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.skirt_length')),
                ('sleeve_lenght', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.sleeve_lenght')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.status')),
                ('style', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.style')),
                ('tallfit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.tallfit')),
                ('telephone_cables', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.telephone_cables')),
                ('type_of_nutrition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.type_of_nutrition')),
                ('very_big', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.very_big')),
                ('volume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.volume')),
                ('waist_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.waist_version')),
                ('warranty_period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.warranty_period')),
                ('warranty_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.warranty_type')),
            ],
        ),
    ]
