# Generated by Django 3.2.4 on 2021-09-27 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_detail', '0002_detail_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_item',
            name='shirt_length',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.shirt_length'),
        ),
    ]
