# Generated by Django 3.2.4 on 2021-09-29 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_detail', '0003_detail_item_shirt_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='active_ingredients',
            options={'verbose_name_plural': 'Active Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='brand_clothes',
            options={'verbose_name_plural': 'Brand Clothes'},
        ),
    ]
