# Generated by Django 3.2.4 on 2021-10-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_detail', '0005_brand_shoe_high_heel_leather_outside_marker_style_shoe_buckle_type_shoe_collar_height_shoe_leather_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_item',
            name='high_heel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.high_heel'),
        ),
        migrations.AddField(
            model_name='detail_item',
            name='leather_outside',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.leather_outside'),
        ),
        migrations.AddField(
            model_name='detail_item',
            name='marker_style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.marker_style'),
        ),
        migrations.AddField(
            model_name='detail_item',
            name='shoe_brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.brand_shoe'),
        ),
        migrations.AddField(
            model_name='detail_item',
            name='shoe_buckle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.shoe_buckle_type'),
        ),
        migrations.AddField(
            model_name='detail_item',
            name='shoe_collar_height',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.shoe_collar_height'),
        ),
        migrations.AddField(
            model_name='detail_item',
            name='shoe_leather_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.shoe_leather_type'),
        ),
        migrations.AddField(
            model_name='detail_item',
            name='shoe_material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.shoe_material'),
        ),
        migrations.AddField(
            model_name='detail_item',
            name='shoe_occasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.shoe_occasion'),
        ),
        migrations.AddField(
            model_name='detail_item',
            name='suitable_width',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_detail.suitable_width'),
        ),
    ]
