# Generated by Django 3.2.4 on 2021-10-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_detail', '0006_auto_20211010_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_item',
            name='packing_type',
        ),
    ]
