# Generated by Django 3.2.4 on 2021-10-10 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_detail', '0007_remove_detail_item_packing_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Packing_type',
        ),
    ]
