# Generated by Django 3.2.4 on 2021-10-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_detail', '0008_delete_packing_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_item',
            name='packing_type',
            field=models.CharField(choices=[('1', 'Free size'), ('2', 'Box')], max_length=20, null=True),
        ),
    ]
