# Generated by Django 3.2.4 on 2021-10-10 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_detail', '0009_detail_item_packing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_item',
            name='cropped_top',
        ),
        migrations.RemoveField(
            model_name='detail_item',
            name='tallfit',
        ),
        migrations.RemoveField(
            model_name='detail_item',
            name='very_big',
        ),
        migrations.DeleteModel(
            name='Cropped_Top',
        ),
        migrations.DeleteModel(
            name='TallFit',
        ),
        migrations.DeleteModel(
            name='Very_big',
        ),
    ]
