# Generated by Django 3.2.4 on 2021-10-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_detail', '0010_auto_20211010_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_item',
            name='cropped_top',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detail_item',
            name='tallfit',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='detail_item',
            name='very_big',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=20, null=True),
        ),
    ]
