# Generated by Django 3.2.4 on 2021-09-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='choice',
            field=models.BooleanField(default=False),
        ),
    ]
