# Generated by Django 3.2.4 on 2021-10-09 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_hitcount_urlhit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HitCount',
        ),
        migrations.DeleteModel(
            name='UrlHit',
        ),
    ]
