# Generated by Django 3.2.4 on 2021-10-01 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_alter_color_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('shipping_unit', models.CharField(max_length=1000)),
                ('charge', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='variation',
            name='price_ship',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='weight',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.shipping'),
        ),
    ]
