# Generated by Django 3.2.4 on 2021-10-01 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20211001_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='charge',
        ),
    ]
