# Generated by Django 3.2.4 on 2021-10-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0009_auto_20211001_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='image',
        ),
        migrations.AddField(
            model_name='variation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='variant/'),
        ),
    ]
