# Generated by Django 3.2.4 on 2021-10-02 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0011_auto_20211002_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='shop',
        ),
        migrations.AddField(
            model_name='shipping',
            name='shop',
            field=models.ManyToManyField(blank=True, to='shops.Shop'),
        ),
    ]
