# Generated by Django 3.2.4 on 2021-10-02 14:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0016_auto_20211002_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='liked',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
