# Generated by Django 3.2.4 on 2021-10-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0020_auto_20211003_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/'),
        ),
    ]
