# Generated by Django 3.2.4 on 2021-10-04 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0021_auto_20211004_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='variant',
        ),
    ]
