# Generated by Django 3.2.4 on 2021-10-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0026_alter_variation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='view',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='view',
        ),
    ]
