# Generated by Django 3.2.4 on 2021-10-09 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0027_auto_20211009_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmodel',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
